### ISSUE TITLE
Kirby's Website no longer has a secret.html

### ISSUE THREAD

**Issue by mozrila** [Purdue-CSUSB/CS-190-F2016#48]
In the lab2 reference sheet, in the "Downloading From the Internet" section should be updated with a new site.   At least temporarily, I put up a new file at http://benweis.me/secret.html.

**Comment by jay-hankins** [comment]
Thanks Ben!

**Comment by jay-hankins** [comment]
Fixed in https://github.com/Purdue-CSUSB/CS-190-F2016/commit/f0b333afbea57b54fb66f8e5997f503b8d1677ce
